nam1 = int(input("enter any number"))
nam2 = int(input("enter any number"))
nam3 = int(input("enter any number"))

print(nam1 + nam2)
print(nam1 - nam2)
print(nam1 / nam2)
print(nam1 * nam2)
print(nam1 + nam3)
print(nam1 - nam3)
print(nam1 / nam3)
print(nam1 * nam3)
print(nam2 + nam3)
print(nam2 - nam3)
print(nam2 / nam3)
print(nam2 * nam3)